TRACK_SEGMENTS = [
    "Andrews I.C.",
    "Andrews - MP 98",
    "Andrews Industry",
    "Rhodo - MP 93.5",
    "Topton - MP 90.2",
    "Nanthahala - MP 86.3",
    "Hewitt - MP 84.5",
    "Wesser - MP 80",
    "Almond - MP 76",
    "Mcclain - MP 75",
    "Fontana - MP 73.5",
    "Brooks - MP 71.2",
    "Alarka Jct. - MP 69",
    "Hemmingway - MP 68",
    "CP W. Bryson - MP 64.5",
    "Bryson - MP 64",
    "CP E. Bryson - MP 63.4",
    "Gov. Island - MP 61.8",
    "Ela - MP 60",
    "Whittier - MP 58",
    "Connelly Creek Wye - MP 57.4",
    "E. Whittier - MP 57",
    "Thomas Valley - MP 54",
    "Wilmot - MP 53.6",
    "Barkers - MP 51",
    "Cowee - MP 49",
    "Dills Yard - MP 48.3",
    "Dills - MP 48",
    "Sylva - MP 46",
    "E. Sylva - MP 45.3",
    "Sylva I.C. - MP 45"
]